Adding Redux
actions and reducer in both Home and AddString Containers
WIP AddString with actions
TODO: dispatch in AddString causes component not to render
	errror message in console:
	index.js?c31f:17 Uncaught TypeError: Object(...) is not a function