Backend redone
No longer using fs to write to txt file as database
BackendData.js changed to instantiate new Backend with empty array
Jest test written for BackendDataRoutes, error upon running
  ERROR: Consider using the "node" test environment.
  though adding docsting results in:
		server/tests/backendDataRoutes.test.js
	events.js:291
	      throw er; // Unhandled 'error' event